"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { categories, formatPrice, products, type Product } from "@/data/catalog";
import { filterProducts, type Filters } from "@/lib/catalog";
import { ProductVisual } from "@/components/catalog/product-visual";
import { CompareButton, CompareTray, useCompareState } from "@/components/catalog/compare-state";

export function SiteHeader() { return <header className="siteHeader"><Link className="wordmark" href="/"><b>SP</b><span>SẢN PHẨM CHÍNH HÃNG<small>Thông tin thật. Lựa chọn đúng.</small></span></Link><nav aria-label="Điều hướng chính"><Link href="/danh-muc/dien-tu">Danh mục</Link><Link href="/thuong-hieu/apple">Thương hiệu</Link><Link href="/kiem-tra">Cách kiểm tra</Link><Link href="/so-sanh">So sánh</Link></nav><div className="headerActions"><Link aria-label="Tìm kiếm" href="/danh-muc/dien-tu">⌕</Link><Link className="headerCta" href="/admin/dang-nhap">Dành cho thương hiệu</Link></div></header>; }
export function MobileHeader() { return <header className="mobileHeader"><Link className="mobileLogo" href="/"><b>SP</b><span>SẢN PHẨM<br/>CHÍNH HÃNG</span></Link><span className="mobileMotto">Sản phẩm thật<br/>Cuộc sống tốt hơn</span><div><button aria-label="Sản phẩm đã lưu">♡</button><button aria-label="Thông báo">♧</button></div></header>; }
export function BarcodeScanButton() { return <Link className="scanButton" href="/kiem-tra" aria-label="Quét barcode hoặc model">⌗<span>Quét mã</span></Link>; }
export function SearchBar({ initialQuery = "", compact = false }: { initialQuery?: string; compact?: boolean }) { const [query, setQuery] = useState(initialQuery); return <form className={`searchBar ${compact ? "compact" : ""}`} action="/danh-muc/dien-tu"><label className="sr-only" htmlFor="catalog-search">Tìm sản phẩm</label><span aria-hidden="true">⌕</span><input id="catalog-search" name="q" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm sản phẩm, model hoặc barcode"/><BarcodeScanButton/>{!compact && <button type="submit">Tìm kiếm</button>}</form>; }
export function CategoryShortcut({ category }: { category: (typeof categories)[number] }) { return <Link className="categoryShortcut" href={`/danh-muc/${category.slug}`}><i aria-hidden="true">{category.icon}</i><strong>{category.name}</strong><small>{category.description}</small><span aria-hidden="true">›</span></Link>; }
export function VerificationSummary() { return <section className="verificationSummary"><i aria-hidden="true">✓</i><div><strong>Đã đối chiếu nguồn</strong><p>Sản phẩm trong nền tảng được kiểm tra, đối chiếu thông tin từ nhiều nguồn đáng tin cậy.</p><small>Cập nhật 12/09/2026</small></div><span aria-hidden="true">›</span></section>; }
export function ProductCard({ product, comparisonIds, onToggle }: { product: Product; comparisonIds: string[]; onToggle: (product: Product) => void }) { const selected = comparisonIds.includes(product.id); return <article className="productCard"><ProductVisual product={product}/><div className="productBody"><p className="productMeta">{product.model} · {product.brand}</p><Link href={`/san-pham/${product.slug}`}><h3>{product.name}</h3></Link><p className="productDescription">{product.description}</p><strong className="productPrice">{formatPrice(product.price)}</strong><Link className="sellerCount" href={`/san-pham/${product.slug}`}>{product.offers.length + 8} nơi bán uy tín <span aria-hidden="true">›</span></Link><CompareButton product={product} selected={selected} onToggle={onToggle}/></div></article>; }
export function BrandCard({ brand }: { brand: string }) { const count = products.filter((product) => product.brand === brand).length; return <Link href={`/thuong-hieu/${products.find((product) => product.brand === brand)?.brandSlug ?? "apple"}`} className="brandCard"><b>{brand.slice(0, 1)}</b><span><strong>{brand}</strong><small>{count} sản phẩm dữ liệu mẫu</small></span><i aria-hidden="true">›</i></Link>; }
export function SellerOfferCard({ offer }: { offer: Product["offers"][number] }) { return <article className="offerCard"><div><strong>{offer.seller}</strong><p>{offer.kind} · Cập nhật {offer.updatedAt}</p></div><div><b>{formatPrice(offer.price)}</b><button type="button">Xem nơi mua</button></div></article>; }
export function FilterPanel({ filters, setFilters, brands }: { filters: Filters; setFilters: (filters: Filters) => void; brands: string[] }) { return <aside className="filterPanel"><div className="filterTitle"><h2>Bộ lọc</h2><button onClick={() => setFilters({})}>Đặt lại</button></div><label>Danh mục<select value={filters.category ?? ""} onChange={(event) => setFilters({ ...filters, category: event.target.value || undefined })}><option value="">Tất cả danh mục</option>{categories.map((category) => <option value={category.slug} key={category.slug}>{category.name}</option>)}</select></label><label>Thương hiệu<select value={filters.brand ?? ""} onChange={(event) => setFilters({ ...filters, brand: event.target.value || undefined })}><option value="">Tất cả thương hiệu</option>{brands.map((brand) => <option value={brand} key={brand}>{products.find((product) => product.brandSlug === brand)?.brand}</option>)}</select></label><label>Giá tham khảo<select value={filters.maxPrice?.toString() ?? ""} onChange={(event) => setFilters({ ...filters, maxPrice: event.target.value ? Number(event.target.value) : undefined })}><option value="">Mọi mức giá</option><option value="2000000">Dưới 2 triệu</option><option value="10000000">Dưới 10 triệu</option><option value="20000000">Dưới 20 triệu</option></select></label><label className="checkField"><input type="checkbox" checked={filters.verifiedOnly ?? false} onChange={(event) => setFilters({ ...filters, verifiedOnly: event.target.checked })}/> Chỉ hiển thị đã đối chiếu nguồn</label></aside>; }
export function EmptyState({ title = "Chưa có dữ liệu mẫu", detail = "Khu vực này sẽ được bổ sung khi dữ liệu được duyệt." }: { title?: string; detail?: string }) { return <div className="emptyState"><span>◌</span><h2>{title}</h2><p>{detail}</p></div>; }
export function NoResultState() { return <EmptyState title="Không tìm thấy sản phẩm phù hợp" detail="Hãy thử tên thương hiệu, model khác hoặc bớt điều kiện lọc."/>; }
export function LoadingSkeleton() { return <div className="skeleton" aria-label="Đang tải nội dung"><i/><i/><i/></div>; }
export function CatalogView({ initialCategory, initialQuery = "" }: { initialCategory?: string; initialQuery?: string }) { const [filters, setFilters] = useState<Filters>({ category: initialCategory, query: initialQuery }); const compare = useCompareState(); const results = useMemo(() => filterProducts(products, filters), [filters]); const brands = [...new Set(products.map((product) => product.brandSlug))]; return <><section className="catalogHero"><p className="eyebrow">KHÁM PHÁ DỮ LIỆU MẪU</p><h1>Tìm và so sánh<br/>có căn cứ.</h1><SearchBar compact/><p>Thông tin giá và nơi mua chỉ để trải nghiệm prototype, luôn kèm thời điểm cập nhật.</p></section><main className="catalogLayout"><FilterPanel filters={filters} setFilters={setFilters} brands={brands}/><section className="catalogResults"><div className="resultHeader"><div><p>{results.length} kết quả</p><h2>Sản phẩm tham khảo</h2></div><label className="mobileSearch">Từ khóa<input value={filters.query ?? ""} onChange={(event) => setFilters({ ...filters, query: event.target.value })}/></label></div>{results.length ? <div className="productGrid">{results.map((product) => <ProductCard key={product.id} product={product} comparisonIds={compare.ids} onToggle={compare.toggle}/>)}</div> : <NoResultState/>}</section></main><CompareTray selected={compare.selected} onRemove={compare.remove} onClear={compare.clear} error={compare.error}/></>; }
export function BrandView({ slug }: { slug: string }) { const compare = useCompareState(); const brandProducts = products.filter((product) => product.brandSlug === slug); const brand = brandProducts[0]?.brand ?? "Thương hiệu"; return <><SiteHeader/><main className="brandPage"><p className="eyebrow">THƯƠNG HIỆU · DỮ LIỆU MẪU</p><h1>{brand}</h1><p>Thông tin thương hiệu và sản phẩm được hiển thị để trải nghiệm prototype. Người dùng cần kiểm tra nguồn chính thức trước khi mua.</p><Link className="brandOfficial" href="#sources">↗ Xem nguồn thông tin</Link><section><div className="sectionHeading"><h2>Sản phẩm tham khảo</h2><span>{brandProducts.length} sản phẩm</span></div>{brandProducts.length ? <div className="productGrid">{brandProducts.map((product) => <ProductCard product={product} comparisonIds={compare.ids} onToggle={compare.toggle} key={product.id}/>)}</div> : <div className="brandList">{["Apple","Samsung","Xiaomi","LocknLock","Bose"].map((item) => <BrandCard brand={item} key={item}/>)}</div>}</section><section id="sources" className="sourceNote"><strong>Phạm vi xác minh</strong><p>Nội dung chỉ mô tả trạng thái đối chiếu nguồn của dữ liệu mẫu, không phải xác nhận độc lập về hàng hóa.</p></section></main><CompareTray selected={compare.selected} onRemove={compare.remove} onClear={compare.clear} error={compare.error}/><MobileBottomNav/></>; }
export function HomeView() { const compare = useCompareState(); return <><MobileHeader/><SiteHeader/><main><section className="homeHero"><div><p className="eyebrow">DỮ LIỆU CÓ NGUỒN · GIÁ CÓ THỜI ĐIỂM</p><h1>Tìm đúng sản phẩm.<br/><em>Chọn đúng nơi mua.</em></h1><p>Tra cứu thông tin nguồn gốc, so sánh sản phẩm và tìm nơi bán uy tín để an tâm hơn trong mỗi lựa chọn.</p><SearchBar/><div className="quickTerms"><span>Gợi ý tìm kiếm:</span>{["iPhone 15","Samsung Galaxy S24","LocknLock","La Roche-Posay"].map((term) => <Link href={`/danh-muc/dien-tu?q=${term}`} key={term}>{term}</Link>)}</div></div><DesktopTrustPanel/></section><section className="homeCategories">{categories.map((category) => <CategoryShortcut category={category} key={category.slug}/>)}</section><div className="mobileOnly"><VerificationSummary/></div><section className="contentSection"><div className="sectionHeading"><div><p className="eyebrow">ĐÃ ĐỐI CHIẾU NGUỒN</p><h2>Được quan tâm</h2><span>Sản phẩm được nhiều người tìm kiếm và so sánh</span></div><Link href="/danh-muc/dien-tu">Xem thêm ›</Link></div><div className="productGrid homeProducts">{products.slice(0,4).map((product) => <ProductCard product={product} comparisonIds={compare.ids} onToggle={compare.toggle} key={product.id}/>)}</div></section><section className="knowledgeBanner"><p>TÌM HIỂU KIẾN THỨC</p><h2>Chọn hàng chính hãng<br/>Sống an tâm mỗi ngày</h2><span>Kiến thức thật. Lựa chọn thông minh.</span><i>›</i></section><DesktopTrustPanel full/><CompareTray selected={compare.selected} onRemove={compare.remove} onClear={compare.clear} error={compare.error}/></main><MobileBottomNav/></>; }
export function DesktopTrustPanel({ full = false }: { full?: boolean }) { return <aside className={full ? "trustPanel full" : "trustPanel"}>{full ? <><h2>3 nguyên tắc tạo nên sự tin cậy tại SẢN PHẨM CHÍNH HÃNG</h2><div className="trustColumns"><TrustItem icon="✓" title="Đối chiếu nguồn" text="Tổng hợp và so sánh thông tin từ nhà sản xuất, nhà phân phối và nguồn đáng tin cậy."/><TrustItem icon="◷" title="Cập nhật theo thời gian thực" text="Giá và thông tin nơi bán được ghi rõ thời điểm."/><TrustItem icon="▤" title="Mở rộng phạm vi xác minh" text="Phân biệt rõ phạm vi dữ liệu được đối chiếu."/></div></> : <><h2>An tâm hơn<br/>với dữ liệu đáng tin cậy</h2><TrustItem icon="✓" title="Đã đối chiếu nguồn" text="Tổng hợp từ nhà sản xuất, nhà phân phối và nguồn đáng tin cậy"/><TrustItem icon="◷" title="Giá có thời điểm" text="Hiển thị thời gian cập nhật"/><TrustItem icon="▤" title="Nơi bán được phân loại" text="Gợi ý nơi bán uy tín, rõ thông tin"/></>}</aside>; }
function TrustItem({ icon, title, text }: { icon: string; title: string; text: string }) { return <div className="trustItem"><i>{icon}</i><span><strong>{title}</strong><small>{text}</small></span></div>; }
export function MobileBottomNav() { return <nav className="bottomNav" aria-label="Điều hướng mobile"><Link href="/">⌂<span>Trang chủ</span></Link><Link href="/danh-muc/dien-tu">▦<span>Danh mục</span></Link><Link className="navCheck" href="/kiem-tra">⌗<span>Kiểm tra</span></Link><Link href="/so-sanh">▥<span>So sánh</span></Link><Link href="/admin/dang-nhap">♙<span>Tài khoản</span></Link></nav>; }
export function CheckView() { const [term, setTerm] = useState(""); const product = products.find((item) => [item.model, item.slug, item.name].some((value) => value.toLowerCase().includes(term.toLowerCase()))) ?? null; const [submitted, setSubmitted] = useState(false); return <><SiteHeader/><main className="checkPage"><p className="eyebrow">KIỂM TRA DỮ LIỆU MẪU</p><h1>Tra cứu model hoặc barcode</h1><p>Đây là công cụ demo. Kết quả cho biết dữ liệu mẫu có mặt trong nền tảng, không phải chứng nhận hàng thật.</p><form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><label htmlFor="check-input">Model, barcode hoặc tên sản phẩm</label><input id="check-input" value={term} onChange={(event) => setTerm(event.target.value)} placeholder="Ví dụ: A3090, SM-S921B"/><button>Kiểm tra</button></form>{submitted && (product ? <article className="checkResult"><span>✓</span><div><p>Đã tìm thấy dữ liệu mẫu</p><Link href={`/san-pham/${product.slug}`}><h2>{product.name}</h2></Link><small>Trạng thái: đã đối chiếu nguồn · Cập nhật {product.updatedAt}</small></div></article> : <NoResultState/>)}</main><MobileBottomNav/></>; }
export function ComparisonView() { const compare = useCompareState(); const items = compare.selected; return <><SiteHeader/><main className="comparisonPage"><p className="eyebrow">SO SÁNH DỮ LIỆU MẪU</p><h1>Đặt các lựa chọn cạnh nhau</h1><p>So sánh tối đa 4 sản phẩm. Giá và nơi mua là thông tin tham khảo tại thời điểm cập nhật.</p>{items.length ? <div className="comparisonTable"><div className="comparisonRow heads"><b>Tiêu chí</b>{items.map((item) => <div key={item.id}><button onClick={() => compare.remove(item.id)} aria-label={`Xóa ${item.name}`}>×</button><Link href={`/san-pham/${item.slug}`}>{item.name}</Link></div>)}</div>{["Giá tham khảo","Thương hiệu","Model","Bảo hành",...Array.from(new Set(items.flatMap((item) => Object.keys(item.specs))))].map((label) => <div className="comparisonRow" key={label}><b>{label}</b>{items.map((item) => <span key={item.id}>{label === "Giá tham khảo" ? formatPrice(item.price) : label === "Thương hiệu" ? item.brand : label === "Model" ? item.model : label === "Bảo hành" ? item.warranty : item.specs[label] ?? "—"}</span>)}</div>)}</div> : <EmptyState title="Chưa chọn sản phẩm để so sánh" detail="Vào danh mục và bấm “So sánh” trên tối đa bốn sản phẩm."/>}</main><MobileBottomNav/></>; }
export function AdminSidebar() { return <aside className="adminSidebar"><Link className="wordmark" href="/"><b>SP</b><span>ADMIN<small>Prototype</small></span></Link>{[["/admin","Tổng quan"],["/admin/san-pham","Sản phẩm"],["/admin/danh-muc","Danh mục"],["/admin/thuong-hieu","Thương hiệu"],["/admin/noi-mua","Nơi mua"],["/admin/kiem-duyet","Kiểm duyệt"]].map(([href,label]) => <Link href={href} key={href}>{label}</Link>)}</aside>; }
export function AdminHeader({ title }: { title: string }) { return <header className="adminHeader"><div><small>CMS DỮ LIỆU MẪU</small><h1>{title}</h1></div><Link href="/" className="headerCta">Xem website ↗</Link></header>; }
export function AdminDataTable({ type }: { type: string }) { const rows: { name: string; detail: string }[] = type === "Sản phẩm" ? products.map((product) => ({ name: product.name, detail: product.model })) : type === "Danh mục" ? categories.map((category) => ({ name: category.name, detail: category.description })) : [...new Set(products.map((product) => product.brand))].map((name) => ({ name, detail: "Dữ liệu mẫu chờ kết nối CMS" })); return <div className="adminTable"><div className="tableToolbar"><input aria-label="Tìm trong bảng" placeholder={`Tìm ${type.toLowerCase()}...`}/><button>+ Thêm dữ liệu mẫu</button></div><table><thead><tr><th>Tên</th><th>Trạng thái</th><th>Cập nhật</th><th>Thao tác</th></tr></thead><tbody>{rows.map((row) => <tr key={row.name}><td><strong>{row.name}</strong><small>{row.detail}</small></td><td><span className="status">Đã đối chiếu nguồn</span></td><td>12/09/2026</td><td><button>⋯</button></td></tr>)}</tbody></table></div>; }
export function AdminView({ title, type = "Sản phẩm" }: { title: string; type?: string }) { return <div className="adminShell"><AdminSidebar/><main className="adminMain"><AdminHeader title={title}/>{title === "Tổng quan" ? <div className="adminDashboard"><div className="metric"><small>Sản phẩm mẫu</small><strong>{products.length}</strong></div><div className="metric"><small>Chờ kiểm duyệt</small><strong>4</strong></div><div className="metric"><small>Nơi mua tham khảo</small><strong>12</strong></div><section><h2>Việc cần xử lý</h2><p>Đây là khung quản trị Sprint 1. Đăng nhập, phân quyền và dữ liệu thật sẽ được xây ở Sprint 2.</p></section></div> : <AdminDataTable type={type}/>}</main></div>; }
